TARRGET_HAS_THIRD_PARTY_APPS := true
BOARD_WPA_SUPPLICANT_DRIVER := true
BOARD_USES_TSLIB := true
BOARD_USES_GENERIC_AUDIO := true
BOARD_USES_ALSA_AUDIO := false
BOARD_WITH_ALSA_UTILS := false

include $(GENERIC_X86_CONFIG_MK)

